FROM nginx:alpine

RUN apk add --no-cache gettext

COPY ./Docker/default.conf /etc/nginx/default.conf

CMD envsubst '${PORT}' < /etc/nginx/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'